### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by NikkyAI** [NikkyAI/pentagame#2]
- Bugs \
  see [issues](https://github.com/NikkyAI/pentagame/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)

- Frontend
  - Redux/Statemachine
    - [ ] process `LobbyEvents`
  - UI
    - [ ] track points for players
    - [ ] change figure shapes for players

- [ ] Notation Parser
  - [ ] finalize notation syntax

- [ ] User
  - [ ] Backend
    - [ ] add User storage (SQLDelight?)
    - [ ] add routes for setting user data (password, displayname)
  - [ ] Frontend
    - [ ] add views
  
- General
  - [ ] add logic and UI for 2v2 and other team modes
  - [ ] Database
